import { SITE } from '@/config/site'
import { formatDate } from '@/lib/format'
import type { AnalysisSession, PublicVerifiedClaim, VerificationTier } from '@/types'

/**
 * Plain-text export of a finished analysis.
 *
 * Previously assembled inline in `ScorePanel`, where it made a presentational
 * component the owner of the export format — and where it dereferenced the
 * rewrite and cover letter unconditionally, both of which are nullable when
 * their generation step fails.
 */

const RULE = '─'.repeat(50)

function section(title: string, body: readonly string[]): string[] {
  return [RULE, title, RULE, '', ...body, '']
}

function numbered(items: readonly string[]): string[] {
  return items.map((item, index) => `  ${index + 1}. ${item}`)
}

/** Group headings, in the same fixed order and the same fixed words as the UI. */
const TIER_HEADING: Record<VerificationTier, string> = {
  verified: 'EVIDENCE FOUND',
  uncertain: 'EVIDENCE UNCLEAR',
  unresolved: 'NOT FOUND IN YOUR CV',
}

const TIER_ORDER: readonly VerificationTier[] = ['verified', 'uncertain', 'unresolved']

/**
 * One claim: the requirement, then the CV text it was matched against.
 *
 * The quote is indented under its requirement rather than run together with it,
 * because the whole point of the export is that a reader can check the finding
 * against their own document without the app in front of them.
 */
function claimLines(claim: PublicVerifiedClaim): string[] {
  const lines = [`  • ${claim.requirement}`, `      ${claim.rationale}`]

  if (claim.evidence_quote !== null) {
    lines.push(`      Cited: "${claim.evidence_quote}"`)
  }

  return lines
}

/**
 * The requirements, grouped by what the evidence check found.
 *
 * This replaces the old flat Matched/Missing/Bonus block, and the difference is
 * not cosmetic: that block asserted three lists of skills as facts about the
 * candidate, with no way to tell where any of it came from. This states what was
 * looked for, what was found, and — for the unresolved group — says in the
 * heading itself that the subject is the document.
 */
function claimSections(claims: readonly PublicVerifiedClaim[]): string[] {
  if (claims.length === 0) {
    return section('REQUIREMENTS', [
      '  No specific requirements could be read from the description provided.',
    ])
  }

  return TIER_ORDER.flatMap((tier) => {
    const group = claims.filter((claim) => claim.verification === tier)
    if (group.length === 0) return []
    return section(`${TIER_HEADING[tier]} (${group.length})`, group.flatMap(claimLines))
  })
}

export function buildReport(session: AnalysisSession): string {
  const { result, mode, rewrite, jobTitle, coverLetter, date } = session
  const { coverage } = result

  const lines: string[] = [
    `${SITE.name.toUpperCase()} — CV ANALYSIS`,
    RULE,
    '',
    `Role: ${jobTitle}`,
    `Mode: ${mode === 'scholarship' ? 'Scholarship' : 'Job Description'}`,
    `Match Score: ${result.score}/100 — ${result.verdict}`,
    `Evidence: ${coverage.verifiedCount} of ${coverage.total} requirements verified`,
    // `session.date`, not `new Date()`: this reports when the analysis ran, not
    // when the file happened to be downloaded. Routed through `formatDate` like
    // every other exported artefact, closing the one call site that formatted
    // dates independently.
    `Analysed: ${formatDate(date)}`,
    '',
    ...claimSections(result.claims),
    ...section('KEY ACTIONS', numbered(result.key_actions)),
    ...section(
      'ATS CHECKS',
      result.ats_checks.map(
        (check) => `  [${check.status.toUpperCase().padEnd(4)}] ${check.label} — ${check.note}`
      )
    ),
    ...section('SALARY', [`  ${result.salary_range}`, `  ${result.salary_context}`]),
    ...section(
      'REWRITTEN CV BULLETS',
      rewrite ? numbered(rewrite.rewritten_bullets) : ['  (Not generated for this analysis.)']
    ),
    ...section('COVER LETTER', [coverLetter ?? '  (Not generated for this analysis.)']),
    RULE,
    '',
    `Generated by ${SITE.name}`,
  ]

  return lines.join('\n')
}

/** Filesystem-safe slug derived from the role title. */
export function reportFilename(jobTitle: string): string {
  const slug = jobTitle
    .slice(0, 30)
    .replace(/[^a-zA-Z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()

  return `careerlens-${slug || 'analysis'}.txt`
}

/** Triggers a client-side download, revoking the object URL afterwards. */
export function downloadTextFile(filename: string, contents: string): void {
  const blob = new Blob([contents], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')

  anchor.href = url
  anchor.download = filename
  anchor.click()

  URL.revokeObjectURL(url)
}
