import { SITE } from '@/config/site'
import type { AnalysisSession } from '@/types'

/**
 * Plain-text export of a finished analysis.
 *
 * Previously assembled inline in `ScorePanel`, where it made a presentational
 * component the owner of the export format — and where it dereferenced the
 * rewrite and cover letter unconditionally, both of which are nullable when
 * their generation step fails.
 */

const RULE = '─'.repeat(50)

function section(title: string, body: readonly string[]): string[] {
  return [RULE, title, RULE, '', ...body, '']
}

function numbered(items: readonly string[]): string[] {
  return items.map((item, index) => `  ${index + 1}. ${item}`)
}

export function buildReport(session: AnalysisSession): string {
  const { result, mode, rewrite, jobTitle, coverLetter } = session

  const lines: string[] = [
    `${SITE.name.toUpperCase()} — OPTIMIZED CV EXPORT`,
    RULE,
    '',
    `Role: ${jobTitle}`,
    `Mode: ${mode === 'scholarship' ? 'Scholarship' : 'Job Description'}`,
    `Match Score: ${result.score}/100 — ${result.verdict}`,
    `Generated: ${new Date().toLocaleDateString('en-GB', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}`,
    '',
    ...section(
      'REWRITTEN CV BULLETS',
      rewrite ? numbered(rewrite.rewritten_bullets) : ['  (Not generated for this analysis.)']
    ),
    ...section('KEY ACTIONS', numbered(result.key_actions)),
    ...section('SKILLS ANALYSIS', [
      `  Matched: ${result.skills_matched.join(', ') || 'None detected'}`,
      `  Missing: ${result.skills_missing.join(', ') || 'None'}`,
      ...(result.skills_extra.length > 0 ? [`  Bonus:   ${result.skills_extra.join(', ')}`] : []),
    ]),
    ...section('COVER LETTER', [coverLetter ?? '  (Not generated for this analysis.)']),
    RULE,
    '',
    `Generated by ${SITE.name}`,
  ]

  return lines.join('\n')
}

/** Filesystem-safe slug derived from the role title. */
export function reportFilename(jobTitle: string): string {
  const slug = jobTitle
    .slice(0, 30)
    .replace(/[^a-zA-Z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()

  return `careerlens-${slug || 'analysis'}.txt`
}

/** Triggers a client-side download, revoking the object URL afterwards. */
export function downloadTextFile(filename: string, contents: string): void {
  const blob = new Blob([contents], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')

  anchor.href = url
  anchor.download = filename
  anchor.click()

  URL.revokeObjectURL(url)
}
